version: "3"

services:
  web:
    build: ../.
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ../.:/app
  nginx:
    image: nginx:1.13
    ports:
      - "8082:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
