export const GAME_BOARD_STROKE_COLOR = "#A8D0E6";
export const GAME_BOARD_SHADOW_COLOR = "#000000";

export const GAME_BOARD_LINE_WIDTH = 0.1;
export const GAME_BOARD_SHADOW_BLUR = 51;
export const GAME_BOARD_SHADOW_OFFSET_X = 9;
export const GAME_BOARD_SHADOW_OFFSET_Y = 28;

export const MOVING_GAME_BLOCK_COLOR = "#374785";
export const ROTATING_GAME_BLOCK_COLOR = "#24305E";
export const GAME_BLOCK_COLOR = "#F76C6C";
export const BLOCKED_GAME_BLOCK_COLOR = "#F8E9A1";

export const GAMEBOARD_ROWS = 15;
export const GAMEBOARD_COLUMNS = 10;
export const GAMEBOARD_CELL_SIZE = 50;
export const GAME_BLOCK_BORDER_WIDTH = 2;
